/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";
import { SearchFilters } from "../filter-bar/SearchFilters.component";
import { SearchOptions } from "../filter-bar/SearchOptions.component";
import { AdditionalFilters } from "../filter-bar/AdditionalFilters.component";
import { SearchActions } from "../filter-bar/SearchActions.component";

@Component({
    selector: "car-search-form",
    template: `
    <section class="car-search-form">
      <header class="form-header">
        <search-filters></search-filters>
        <button class="save-search-btn">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/293e821b836f8462b770ffbc4cdde8f3e652066491df859d504db4bb779c58ee?placeholderIfAbsent=true&apiKey=42475809f4c148fa9ae1fe84d7b1a359"
            alt=""
            class="save-icon"
          />
          <span>Сохранить поиск</span>
        </button>
      </header>
      <search-options></search-options>
      <additional-filters></additional-filters>
      <search-actions></search-actions>
    </section>
  `,
    styles: [
        `
      .car-search-form {
        border-radius: 20px;
        background-color: #fff;
        box-shadow: 0 12px 16px -4px rgba(16, 24, 40, 0.08);
        display: flex;
        margin-top: 24px;
        width: 100%;
        flex-direction: column;
        overflow: hidden;
        font-family: Montserrat, sans-serif;
        padding: 34px;
      }
      .form-header {
        display: flex;
        width: 100%;
        gap: 20px;
        flex-wrap: wrap;
        justify-content: space-between;
      }
      .save-search-btn {
        align-self: start;
        display: flex;
        gap: 12px;
        font-size: 14px;
        color: #0066cc;
        font-weight: 600;
        background: none;
        border: none;
        cursor: pointer;
      }
      .save-icon {
        width: 22px;
        height: 22px;
      }
      @media (max-width: 991px) {
        .car-search-form {
          max-width: 100%;
          padding: 0 20px;
        }
      }
    `,
    ],
    imports: [
        CommonModule,
        SearchFilters,
        SearchOptions,
        AdditionalFilters,
        SearchActions,
    ]
})
export class CarSearchFormComponent {}
