/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";

@Component({
    selector: "additional-filters",
    template: `
    <div class="additional-filters">
      <button class="filter-btn">
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/4d440792acfba3d9dc9be273da2377afec43beb00a94825e449638ca9648e559?placeholderIfAbsent=true&apiKey=42475809f4c148fa9ae1fe84d7b1a359"
          alt=""
          class="filter-icon"
        />
        <span>Гарантия</span>
      </button>
      <button class="filter-btn">
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/835960d8a99bb9edec8c79f431af2a976c7269c3d595328d207e106ae856f121?placeholderIfAbsent=true&apiKey=42475809f4c148fa9ae1fe84d7b1a359"
          alt=""
          class="filter-icon"
        />
        <span>Проверено</span>
      </button>
      <button class="filter-btn">
        <span class="discount-badge">0.1%</span>
        <span>Рассрочка</span>
      </button>
      <button class="filter-btn">
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/bbf96f587ad9fd00343a32dc54ff719f4ea011aa5d7b9ddb4287584afb6108cb?placeholderIfAbsent=true&apiKey=42475809f4c148fa9ae1fe84d7b1a359"
          alt=""
          class="filter-icon"
        />
        <span>Кредит</span>
      </button>
      <button class="filter-btn">
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/a4601f9819a25664f3f3b79eedf7b6721f2ef2ffc6e6e9bfb27ff68e4ad2c852?placeholderIfAbsent=true&apiKey=42475809f4c148fa9ae1fe84d7b1a359"
          alt=""
          class="filter-icon"
        />
        <span>Растаможен</span>
      </button>
      <button class="filter-btn">
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/2bb43d4e13b0a678b7c4e7f1510ead63f9dfe12157f095105f8200e24730331c?placeholderIfAbsent=true&apiKey=42475809f4c148fa9ae1fe84d7b1a359"
          alt=""
          class="filter-icon"
        />
        <span>Купить за бонусы</span>
      </button>
    </div>
  `,
    styles: [
        `
      .additional-filters {
        display: flex;
        margin-top: 24px;
        gap: 16px;
        line-height: 2;
        flex-wrap: wrap;
      }
      .filter-btn {
        border-radius: 8px;
        background-color: #f3f7fe;
        display: flex;
        gap: 8px;
        font-size: 14px;
        color: #101828;
        font-weight: 500;
        padding: 11px 16px;
        border: none;
        cursor: pointer;
        align-items: center;
      }
      .filter-icon {
        width: 18px;
        height: 18px;
      }
      .discount-badge {
        border-radius: 3px;
        background-color: #f04438;
        font-size: 10px;
        color: #fff;
        font-weight: 600;
        text-align: center;
        padding: 2px 4px;
      }
    `,
    ],
    imports: [CommonModule]
})
export class AdditionalFilters {}
