/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";

@Component({
  selector: "search-actions",
  template: `
    <div class="search-actions">
      <button class="advanced-search-btn">
        <span>Расширенный поиск</span>
        <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/b077f643840d4957e5dde99bdf91f62c977ee53caf04762c312bef4a0fdc9d24?placeholderIfAbsent=true&apiKey=42475809f4c148fa9ae1fe84d7b1a359" alt="" class="advanced-icon" />
      </button>
      <button class="show-results-btn">Показать 18 307 авто</button>
    </div>
  `,
  styles: [`
    .search-actions {
      display: flex;
      margin-top: 24px;
      width: 100%;
      gap: 20px;
      font-size: 14px;
      font-weight: 600;
      text-align: center;
      flex-wrap: wrap;
      justify-content: space-between;
    }
    .advanced-search-btn {
      display: flex;
      gap: 8px;
      color: #0066cc;
      background: none;
      border: none;
      cursor: pointer;
      align-items: center;
    }
    .advanced-icon {
      width: 22px;
      height: 22px;
    }
    .show-results-btn {
      border-radius: 14px;
      background-color: #0066cc;
      color: #fff;
      padding: 17px 55px;
      border: none;
      cursor: pointer;
    }
    @media (max-width: 991px) {
      .search-actions {
        max-width: 100%;
      }
      .show-results-btn {
        padding: 17px 20px;
      }
    }
  `],
  standalone: true,
  imports: [CommonModule],
})
export class SearchActions {}
